version: '3'
services:
  # Enrichment API
  data-api:
    build:
      context: .
      dockerfile: docker/DockerfileAPI
    image: maayanlab/enrichmentapi:1.3.2
    environment:
      token: token
      AWS_BUCKET: bucket
      AWS_BUCKET_PATH:
      AWS_ACCESS_KEY_ID: awsaccesskey
      AWS_SECRET_ACCESS_KEY: awssecret
      AWS_ENDPOINT_URL: http://minio:9000
      S3_AUTOLOAD: 'true'
    ports:
      - 8080:8080

  # An S3 compliant store
  minio:
    image: minio/minio
    entrypoint: >
      /bin/sh -c "
        mkdir -p /data/$${MINIO_BUCKET};
        minio server /data;
        exit 0"
    environment:
      MINIO_BUCKET: bucket
      MINIO_ACCESS_KEY: awsaccesskey
      MINIO_SECRET_KEY: awssecret
    # Expose minio web UI
    # ports:
    #   - 9000:9000
    # Persist minio volume
    # volumes:
    #   - minio:/data
