version: '3'
services:
  # Enrichment API
  data-api:
    build:
      context: .
      dockerfile: docker/DockerfileAPI
    image: maayanlab/enrichmentapi
    environment:
      SPRING_APPLICATION_JSON: '{ "ignite": { "addresses": "ignite-1,ignite-2", "clientPort": 10800, "communicationSPIPort": 47100, "discoverySPIPort": 47500, "restPort": 11211, "storage": "/opt/data", "addToBaselineTopology": false  } }'
      token: token
      AWS_BUCKET: bucket
      AWS_ACCESS_KEY_ID: awsaccesskey
      AWS_SECRET_ACCESS_KEY: awssecret
      AWS_ENDPOINT_URL: http://minio:9000
    ports:
      - 8080:8080

  # Ignite Cluster
  ignite-1:
    image: apacheignite/ignite:2.7.0
  ignite-2:
    image: apacheignite/ignite:2.7.0

  # An S3 compliant store
  minio:
    image: minio/minio
    entrypoint: >
      /bin/sh -c "
        mkdir -p /data/$${MINIO_BUCKET};
        minio server /data;
        exit 0"
    environment:
      MINIO_BUCKET: bucket
      MINIO_ACCESS_KEY: awsaccesskey
      MINIO_SECRET_KEY: awssecret
    # Expose minio web UI
    # ports:
    #   - 9000:9000
    # Persist minio volume
    # volumes:
    #   - minio:/data
