version: '3'
services:
  data-api:
    build:
      context: .
      dockerfile: docker/DockerfileAPI
    image: maayanlab/enrichmentapi
    environment:
      SPRING_APPLICATION_JSON: '{ "ignite": { "addresses": "ignite-1,ignite-2", "clientPort": 10800, "communicationSPIPort": 47100, "discoverySPIPort": 47500, "restPort": 11211, "storage": "/opt/data", "addToBaselineTopology": false  } }'
      token: token
    ports:
      - 8080:8080
  ignite-1:
    image: apacheignite/ignite:2.7.0
  ignite-2:
    image: apacheignite/ignite:2.7.0
