server:
  port:
    8080
ignite:
  addresses:
    ignite:8446, ignite:8446
  clientPort:
    8443
  restPort:
    8444
  communicationSPIPort:
    8445
  discoverySPIPort:
    8446
  storage:
    /opt/data
  addToBaselineTopology:
    true

logging:
  file: ./logs.log
  level:
    enrichmentapi.calc: DEBUG